### ISSUE TITLE
Add Support for HMAC-SHA512 Authentication Method

### ISSUE THREAD

**Issue by DanielThePear** [ctrezevant/PyEdsby#13]
Hello!
I saw that PyEdsby had been fixed and attempted to make a program with it. However, when I try to create an edsby.Edsby session, it fails during authentication. Here is the error traceback:
`Traceback (most recent call last):
  File "d:\Code Projects\New Like Bot\Main.py", line 3, in <module>
    EdsbySession = Edsby(host="notmyschool.edsby.com", username="YouCantSeeMyName", password="NoPasswordForYou")
  File "d:\Code Projects\New Like Bot\edsby.py", line 54, in __init__
    self.login(username=kwargs['username'], password=kwargs['password'])
  File "d:\Code Projects\New Like Bot\edsby.py", line 61, in login
    self.studentData = self.sendAuthenticationData()
  File "d:\Code Projects\New Like Bot\edsby.py", line 197, in sendAuthenticationData
    'session_id_edsby': dict(studentData.cookies)['session_id_edsby'],
KeyError: 'session_id_edsby'`

After further investigation, I learned that the POST request in `sendAuthenticationData()` is not returning any cookies.

I will continue to look into this issue myself, though help would be appreciated.

**Comment by chtzvt** [comment]
Hey Daniel, thanks for reaching out. There’s a possibility that this is either a bug, or potentially caused by differences in Edsby deployments. Unfortunately I’m still unable to look into the issue personally, as I have no Edsby instances to test with...

@NatRoi - Is this something you could look into?

**Comment by nroize** [comment]
I tried entering an invalid password and got the same error:
`Traceback (most recent call last):
  File "g:/PyEdsby/placetests.py", line 4, in <module>
    edsby = Edsby(host='alsonotmyschool.edsby.com', username='test', password='test1234')
  File "g:\PyEdsby\edsby.py", line 54, in __init__
    self.login(username=kwargs['username'], password=kwargs['password'])
  File "g:\PyEdsby\edsby.py", line 61, in login
    self.studentData = self.sendAuthenticationData()
  File "g:\PyEdsby\edsby.py", line 196, in sendAuthenticationData
    'session_id_edsby': dict(studentData.cookies)['session_id_edsby'],
KeyError: 'session_id_edsby'`

So at least at first glance, it looks like this might be caused by an incorrect username/password. If you're sure that you've entered your username, password, and host correctly, you could try adding `print(studentData.json())` after the post request (line 194) to see if there's an error being returned.

**Comment by DanielThePear** [comment]
> I tried entering an invalid password and got the same error:
> `Traceback (most recent call last): File "g:/PyEdsby/placetests.py", line 4, in <module> edsby = Edsby(host='alsonotmyschool.edsby.com', username='test', password='test1234') File "g:\PyEdsby\edsby.py", line 54, in __init__ self.login(username=kwargs['username'], password=kwargs['password']) File "g:\PyEdsby\edsby.py", line 61, in login self.studentData = self.sendAuthenticationData() File "g:\PyEdsby\edsby.py", line 196, in sendAuthenticationData 'session_id_edsby': dict(studentData.cookies)['session_id_edsby'], KeyError: 'session_id_edsby'`
> 
> So at least at first glance, it looks like this might be caused by an incorrect username/password. If you're sure that you've entered your username, password, and host correctly, you could try adding `print(studentData.json())` after the post request (line 194) to see if there's an error being returned.

I got the error when I entered the correct username and password.
I did what you suggested and added `print(studentData.json())` after the POST request, and it did indeed return an error:
`{'error': 1003, 'when': '2021-03-23 15:34:35', 'errorstr': 'Bad Username or Password', 'errorfield': '*password', 'sauthdata': 'Not going to send this in case it can be used to compromise my account'}`

I do not believe that this problem is actually caused by user error (Incorrect password). Below, I've listed and explained every problem I found with PyEdsby.

Abstract summary of the problems listed below: There are a few minor oversights and formatting errors, but the main issue is that there are several data fields of unknown origin missing from the login request, and they are required for a successful login.

Function `getAuthData()`:

- When making the request, PyEdsby is providing **Plaintext-LeapLDAP** as the type for encryption. The correct type is **HMAC-SHA-512**. The function also returns the constant **LeapLDAP** for **crypttype**. Furthermore, **crypttype** is the incorrect key, as Edsby expects the key to be named **login-crypttype**.
- This function is returning **login-password** in plaintext, for use in `sendAuthenticationData()`, though `sendAuthenticationData()` no longer directly uses the plaintext password.

Function `sendAuthenticationData()`:

_This part of the authentication sequence is what stumped me. I can't figure out where most of the data fields in the login request originate from._

- The **_formkey** field has no problems, it is taken directly from the `fetchcryptdata` request.
- The **sauthdata** field has no problems, it is taken directly from the `fetchcryptdata` request.
- The **login-userid** field has no problems, it is taken directly from user input.
- The **remember** field has no problems.

- The **login-host** field is formatted incorrectly, PyEdsby is using the full domain (I.e. **myschool.edsby.com**), though Edsby expects the shortened version (I.e. **myschool**)
- The **login-crypttype** field should have **HMAC-SHA-512** as the value, instead of **LeapLDAP**.
- **login-cauthdata**: This is completely missing from PyEdsby. It needs to be included in the request.
- **login-extendedpasswords**: This is completely missing from PyEdsby. It needs to be included in the request.
- **login-password**: This is not missing from PyEdsby, but, PyEdsby is providing a plaintext version of the password, whereas Edsby expects some encoded string.

I am unable to determine the origin of **login-cauthdata** + **login-extendedpasswords**, and I can't figure out how **login-password** is being encoded.

**Edit**: I found two functions in the request call stack that could pertain to the problem: `do_login_pw_encrypt` and `initiate_encryption`. I will investigate and attempt to reverse-engineer these in Python, but help is appreciated since I have a very  basic grasp of JS.

**Comment by nroize** [comment]
My Edsby instance still only uses plaintext/LeapLDAP for the `loginform` and `fetchcryptdata` requests. Could different hosts have different password encryption methods?

Edit: that is, it still works despite missing all of that information you mentioned, and only sending requests using LeapLDAP. I suppose the only rational explanation is that different hosts have different encryption now, or Edsby is rolling out new encryption on a host-by-host basis (or something along those lines).

Edit 2: turns out that Edsby supports self-hosted passwords. All of the instances that I've tried were self-hosted and used LeapLDAP. Yours hosts passwords on Edsby's own servers, so it uses SHA-512. I don't have access to any instances that do that, so if anyone can implement that as an option in the login methods it would be much appreciated!

**Comment by DanielThePear** [comment]
Thanks for the quick reply!
I don't know what you mean by self-hosted passwords, nor how that ties into the encryption type. I'm confused as to how I should proceed from here.

Would you be able to help with this if I told you the name of my Edsby instance? You are able to analyze all of the web requests significant to this project whether the login fails or succeeds, so you don't need a password to look into how the login sequence works.

**Comment by nroize** [comment]
I could definitely give it a shot!

What I mean by self-hosted is that Edsby gives schools the option to host their own password server, so that they can have a unified password database (e.g. students have the same password for school computers as Edsby). Those seem to use LeapLDAP, whereas the password servers that Edsby keeps (for schools that do not self-host) are SHA-512.

**Comment by DanielThePear** [comment]
Thanks for the explanation!
My Edsby domain is `mentorteam.edsby.com`.

**Comment by chtzvt** [comment]
Hello all!

I figured I'd drop in with some guidance on how to handle this, especially given that it looks like we're going to end up with multiple login flows that'll need to coexist in the project.

@DanielThePear's analysis is thorough, and there are some key points I'll mention that are helpful in diagnosing their particular issue. **This is not a problem with the current LDAP authentication flow** implemented by PyEdsby. Rather, the underlying issue is that the authentication method used in @DanielThePear's Edsby instance is not supported in the current implementation.

### Analysis

I had a brief look at @DanielThePear's Edsby instance. The login page appears to be generating an [HMAC](https://en.wikipedia.org/wiki/HMAC)-[SHA512](https://en.wikipedia.org/wiki/SHA-2) hash using a custom implementation that includes some extra nonces/values retrieved when the client bootstraps.

Based on my brief analysis, the client fetches some configuration information from `/core/login.json/<id>?xds=loginform` to determine the authentication schemes it should use for login (`HMAC-SHA-512;Plaintext;EdsbyTicket`, in this case). The client then requests `/core/node.json/<id>?xds=fetchcryptdata&type=HMAC-SHA-512` to fetch additional encryption parameters. The actual encryption routines are implemented client-side in `engine.min.js`.

If you beautify `engine.min.js` you can start to see what's going on with the implementation. The Edsby client's crypto module begins with `cf.module("crypt", function(e, t, i, n) {` starting on line 47850 in the beautified version of `engine.min.js` I'm looking at. I don't want to risk receiving DMCA notices from CoreFour for posting/reverse-engineering their code, so I'll instead provide a list of important function signatures along with some analysis.

First- some of the minified methods are exported using human-readable names from the `crypt` module, which provides a useful reference:
```
[...]
doPWEncrypt: V,
processPreCryptData: q,
selectBestSupportedCryptType: Y,
cryptTypeNeedsNewServerData: G,
setServerNonce: J,
generateCryptClientData: X,
doAuthCrypt: Q,
get_url_parameter: Z,
[...]
```

Other relevant method signatures:

- `function Q(e, t, i, n, a, r, o, s, l)`: Maps to `doAuthCrypt`. Setting a [breakpoint](https://developer.chrome.com/docs/devtools/javascript/breakpoints/#loc) on line 49871 (where I see this called by `do_login_pw_encrypt`) reveals the following information about the parameters:
	- `e`: A string containing the algorithm, `HMAC-SHA-512`.
	- `t`: An empty array.
	- `i`: The username input element `#\32 loginform-login-userid__f__`
	- `n`: The password input element `#\32 loginform-login-password__f__`
	- `a`: A hidden form element `#\32 loginform-login-sauthdata`, containing the `sauthdata` token.
	- `r`: A hidden form element `#\32 loginform-login-cauthdata`, containing the `cauthdata` token.
	- `o`: A hidden form element `#\32 loginform-login-crypttype`. This has no value initially, but is submitted as `HMAC-SHA-512` in the login POST request.
	- `s`: A string of format `sha512:<some GUID>`. This value is returned from the server in `/core/login.json/<id>?xds=loginform` when the client bootstraps.
	- `l`: A hidden form element `#\32 loginform-login-extendedpasswords`. This has no value initially, but is submitted with some calculated hash in the login POST.

- `function V(e, t, i)`: Maps to `doPWEncrypt`.
- `initiate_encryption: function(t, i, n)`: Appears to handle the bootstrapping logic described earlier for the client cryptography routines.
- `do_login_pw_encrypt: function(t, i, a)`: Handles login form password encryption depending on the configured encryption type. Logic in this function appears to dispatch the appropriate algorithm and trigger the POST request.
- `do_credential_update_encrypt: function(t, i, a)`: Similar to `do_login_pw_encrypt`, but this appears to be specific to password resets.

### Recommended Next Steps

PyEdsby is a bespoke library supported by unpaid volunteers. that's not supported by CoreFour in any way, and our resources are limited. I  won't proceed further with reverse-engineering because I don't have a stake in implementing this functionality, but the information above should lay the foundation for a solid start to do so.

If I were in @DanielThePear's shoes, I'd take the following approach:

- Begin the process of un-minifying and analyzing `engine.min.js` using a combination of static code review and runtime analysis (the latter is best done in the browser using the [Chrome devtools debugger](https://developer.chrome.com/docs/devtools/javascript/reference/)).
	- You don't need to reverse-engineer the hashing/digest algorithms themselves per se, but you want to generally understand the operations being applied and what values are being used to generate the hashes.
- Once you've got a solid understanding of the above, you can work on replicating those operations in Python.
	- Don't worry about implementing cryptographic algorithms from scratch here. Ideally, the [hashlib](https://docs.python.org/3/library/hashlib.html) and [hmac](https://docs.python.org/3/library/hmac.html) modules will cover this.

Here's a small test harness to get you started on that last point:

```
import hashlib
import hmac
import base64

# You'll need to study the Edsby implementation to determine what values to use for these
hmac_secret = ""
hmac_value_to_sign = ""

# You'll want to test other encodings as well (such as UTF-16, ASCII, etc)
# see https://mathiasbynens.be/notes/javascript-encoding
encoding = "UTF-8"

if __name__ == '__main__':
    mac = hmac.new(bytes(hmac_secret, encoding), bytes(hmac_value_to_sign, encoding), hashlib.sha512);
    print(mac.hexdigest())
```

Assuming that you're willing to go through with the above, we would welcome support for this authentication type in PyEdsby!

### Alternative, Easier Approach

If you'd prefer to use PyEdsby without implementing support for this feature, you can manually import your session cookies as described in the [documentation](https://github.com/ctrezevant/PyEdsby/wiki/Documentation). This will allow PyEdsby to interact with your Edsby instance for the lifetime of that particular session, after which you'll need to reauthenticate and import a fresh set of session cookies.

---

### Plan for PyEdsby Maintainers

@NatRoi

I'll cover my thoughts on a modular authentication approach in a separate issue- stay tuned! :)

**Comment by DanielThePear** [comment]
Thanks for looking into it! This is super helpful -I didn't even know what Chrome's debugger could do until you mentioned it in your comment. I will begin reverse-engineering the authentication sequence once I have some time, probably when I finish my Calculus course in a few weeks.

**Comment by chtzvt** [comment]
@DanielThePear Another user at your institution has reached out to me (via email) in regards to this issue. I've pointed them to this thread in hopes that the both of you can connect and collaborate, if there's still interest.

**Comment by DanielThePear** [comment]
Awesome, thanks!
